### ISSUE TITLE
Glitch image without interval/timer function?

### ISSUE THREAD

**Issue by iamaz007** [kyu-suke/f_glitch#3]
Hi, your package is great. can you add an option in which it doesn't require frequency parameter. so, glitch effect will be applied without any animation (timer) on simple image and animation can be applied on gif. I'm looking something like this. https://pypi.org/project/glitch-this/

**Comment by kyu-suke** [comment]
Hello! Thanks for your comment. Do you mean you want to use `FGlitch` widget without glitch effects when you apply animation gif image? In that case, is there a difference to use `Image` widget?
Or do you mean you want to create gif image with Flutter? The URL you are written in seems a package create glitched animation gif.

Thanks!

**Comment by iamaz007** [comment]
This is what I want, when I pass image to `FGlitch` this should return an image with just color offsets at random position (pixels), that's it. Right now, `FGlitch` returns glitch with an interval of 1000 ms (default), I don't want any interval, just want image with its color offset at random position and when I increase the glitch value (through slider) noise in image should increase. 
If you test this package in python https://pypi.org/project/glitch-this/ with .png or .jpeg image, it will return image with color offset and noise in it. this is exactly what I needed in FGLitch as a feature
Hope you got my point. 
Thanks

**Comment by kyu-suke** [comment]
Thanks for your explanation! I get your point. I will try to develop this feature.

**Comment by kyu-suke** [comment]
@iamaz007 
Hi! I publish new version `0.1.0`. Could you check the version? I would be happy to fulfill your request.
