### ISSUE TITLE
ColorFiltered channel widget

### ISSUE THREAD

**Issue by feduke-nukem** [kyu-suke/f_glitch#7]
Hello,

Awesome widget. I wonder if there is a way to apply multiple ColorFiltered to image before it will be processed as channelWidget?
I need to cover my images with specified colors and blendModes by then I lose the "RGB SPLIT" effect. @kyu-suke

**Comment by kyu-suke** [comment]
Hello, @feduke-nukem 

Thanks for your comment!
Maybe there is no way now.
Is it correct that you want to use an image with some blend mode applied to this widget?
I would appreciate it if you could provide specific examples of use.

Thanks!

**Comment by feduke-nukem** [comment]
> Hello, @feduke-nukem
> 
> Thanks for your comment! Maybe there is no way now. Is it correct that you want to use an image with some blend mode applied to this widget? I would appreciate it if you could provide specific examples of use.
> 
> Thanks!

Yes, that's correct. I need to provide a couple of ColorFiltered on "glitched" widget, but in such case I am losing "rgb shift effect" visibility.

I was trying to modify the inner code like this:

```dart
 Widget _channelWidget(_ColorChannel cc) {
    return Positioned.fill(
      left: cc.leftPosition,
      top: cc.topPosition,
      child: _BlendMask(
        blendMode: BlendMode.lighten,
        child: ColorFiltered(
          colorFilter: ColorFilter.mode(cc._color, BlendMode.modulate),
          child: ColorFiltered(
            colorFilter: ColorFilter.mode(
                Colors.purple.withOpacity(0.8), BlendMode.hardLight),
            child: ColorFiltered(
              colorFilter: const ColorFilter.mode(Colors.red, BlendMode.color),
              child: Image(
                image: widget.imageProvider,
                fit: widget.imageFit,
              ),
            ),
          ),
        ),
      ),
    );
  }
  ```
  
  But it seems that _BlendMask is only working when the cc._color is provided to the Image only, not the ColorFiltered.
  The idea is somehow to cover first the image with ColorFiltered and only after do the rgb shift.
  
  Like the only way now that I found is to take the screenshot of "filtered" image widget and after that apply on it "rgb shift". But that's very weak solution

**Comment by feduke-nukem** [comment]
I ended up with such additional class
```dart
class _ColorFilterMask extends SingleChildRenderObjectWidget {
  final ColorFilter colorFilter;

  const _ColorFilterMask({
    required this.colorFilter,
    Key? key,
    Widget? child,
  }) : super(key: key, child: child);

  @override
  RenderObject createRenderObject(context) {
    return _RenderColorFilterMask(colorFilter);
  }

  @override
  void updateRenderObject(
      BuildContext context, _RenderColorFilterMask renderObject) {
    renderObject.colorFilter = colorFilter;
  }
}

class _RenderColorFilterMask extends RenderProxyBox {
  ColorFilter colorFilter;

  _RenderColorFilterMask(this.colorFilter);

  @override
  void paint(context, offset) {
    context.canvas.saveLayer(
      offset & size,
      Paint()..colorFilter = colorFilter,
    );

    super.paint(context, offset);

    context.canvas.restore();
  }
}
```

Which can replace individual Image.color and Image.colorBlendMode and apply other colors like so:

```dart
  Widget _channelWidget(_ColorChannel cc) {
    return Positioned.fill(
      left: cc.leftPosition,
      top: cc.topPosition,
      child: _BlendMask(
        blendMode: BlendMode.lighten,
        child: _ColorFilterMask(
          colorFilter: ColorFilter.mode(cc._color, BlendMode.modulate),
          child: _ColorFilterMask(
            colorFilter: ColorFilter.mode(
                Color(0xFF4D052A).withOpacity(0.9), BlendMode.hardLight),
            child: _ColorFilterMask(
              colorFilter: ColorFilter.mode(
                  Color(0xFF9824F2), BlendMode.color),
              child: Image(
                image: widget.imageProvider, 
                fit: widget.imageFit, 
              ),
            ),
          ),
        ),
      ),
    );
  }
  ```
